site_name: Joint MUSE/IRIS Science Team Meeting, October 27-30 2025
site_author: LOC
site_url: https://lm-sal.github.io/iris_muse_team_meeting/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  locale: en
  logo: assets/images/cover_rect.jpg
  favicon: assets/images/cover_rect.jpg
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - toc.follow
  palette:
    - scheme: muse
copyright: Copyright &copy; 2025-2026 - MUSE/IRIS LOC
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3
nav:
  - Home: index.md
  - About: about.md
  - Registration: registration.md
  - Information: useful_info.md
  - Schedule: schedule.md
  - Participants: participants.md
  - Abstracts: abstracts.md
  - Instructions: instructions.md
plugins:
  - search
  - table-reader
  - spellcheck:
      backends:
      - codespell:
          dictionaries: [clear, rare]
      known_words: [ake, ]
      ignore_code: yes
      min_length: 2
      allow_unicode: no
      strict_only: yes
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - social:
      cards_layout_options:
        background_color: "#DAD5B9"
        color: "#4833C8"

extra:
  generator: false
