site_name: Joint MUSE/IRIS science team meeting, October 27-30 2025
site_author: LOC Team
site_url: https://iris_muse_team_meeting.seti.org
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: overrides
  locale: en
  logo: assets/images/cover_square.jpg
  favicon: assets/images/favicon.png
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - toc.follow
  palette:
    - scheme: muse_light
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: muse
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
copyright: Copyright &copy; 2025-2026 - SETI
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3
nav:
  - Home: index.md
  - About: about.md
  - Registration: registration.md
  - Information: useful_info.md
  - Participants: participants.md
  - Abstracts: abstracts.md
  # - Schedule:
  #   - Talk Schedule: schedule/full_schedule.md
  #   - Keynote Speakers: schedule/keynotes.md
  #   - Tutorials: schedule/tutorials.md
  #   - Talks: schedule/talks.md
  - Instructions: instructions.md
  #- Social Events: social_events.md
  - FAQ: faq.md
  #- Sponsors:
  #  - our-sponsors.md
plugins:
  - search
  - table-reader
  - social:
      cards_layout_options:
        background_color: "#DAD5B9"
        color: "#4833C8"

extra:
  generator: false
